### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by humbertosales** [rgarita/docker-fountainjs#1]
> @ build /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain
> gulp

[21:47:10] Loading /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/gulp_tasks/browsersync.js
[21:47:10] Loading /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/gulp_tasks/karma.js
[21:47:13] Loading /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/gulp_tasks/misc.js
[21:47:13] Loading /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/gulp_tasks/webpack.js
[21:47:15] Using gulpfile /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

npm info lifecycle @~build: Failed to exec build script
npm ERR! Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/app/fountain/workspaceAplicacao/classificados/clienteFountain/npm-debug.log

**Comment by humbertosales** [comment]
Solved in Dockerfile:

```
RUN npm i -g gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb
RUN npm i -g yo generator-fountain-webapp generator-fountain-react generator-fountain-angular1 generator-fountain-angular2 && \
    npm cache clean
```
